version: "3.9"

services:
  influxdb:
    image: influxdb:2.7.11
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  telegraf:
    image: telegraf:1.33
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana-oss:11.4.0
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.0.14
    restart: always
    volumes:
      - /home/anushka/Documents/GitHub/tig-stack-influxdb/mosquitto/config:/mosquitto/config
      - /home/anushka/Documents/GitHub/tig-stack-influxdb/mosquitto/data:/mosquitto/data
      - /home/anushka/Documents/GitHub/tig-stack-influxdb/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    


volumes:
  grafana-storage:
  influxdb-storage:
